### PR TITLE
fix: g3 matcher function + tests

### PR DESCRIPTION
**Pull request by Zat42**
Fix an issue where [add_mapping_policies/2](https://github.com/casbin/casbin-ex/blob/master/lib/acx/enforcer_server.ex#L91) is never called because if [this](https://github.com/casbin/casbin-ex/blob/master/lib/acx/enforcer_server.ex#L94).

I also added some tests for this.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Zat42 hi, may I ask why you contribute to this project?

**Comment by Zat42** [comment]
@hsluoyz Hi, I plan to use it for some projects.

**Comment by hsluoyz** [comment]
@Zat42 great!

**Comment by hsluoyz** [comment]
@ngoclinhng plz review

**Review by ngoclinhng — APPROVED** [review]
Great job buddy!

**Pull request merged**
