### PR TITLE
WIP: Add Domain to RBAC

### LINKED ISSUE #4: Support for domain based rbac model
https://github.com/casbin/casbin/blob/master/examples/rbac_with_domains_model.conf

### PR DESCRIPTION
**Pull request by ssajnani**
Fix: https://github.com/casbin/casbin-ex/issues/4

# Description

1. Add a new function for stub for 3 arg group functions.
2. Add tests for new stubs
3. Domain is concatenated to the sub to create a new vertex (uniqueness constraint)
4. Adding more test cases

### CODE REVIEW

**Comment by hsluoyz** [comment]
@ssajnani fix all checks and link your GitHub to your commits:

image

**Comment by hsluoyz** [comment]
@ssajnani

**Comment by ngoclinhng** [comment]
Looks pretty good to me, but: 

1. Inconsistent indentation styles (_between yours and the current style)_:
   - This makes it pretty damm hard to know what **_real changes are_** have been made.
   - In order to merge your commit into the master branch, we have to either re-style our code according to your indentation-level or yours according to ours.

2. Since I have been away from the entire code base for more than two years(?), I need more time to review the whole code base again as well as your commit.
3. Last but not least: I would like to apologize for the (_far too_) late response to you both @hsluoyz @ssajnani

**Comment by hsluoyz** [comment]
@ssajnani

**Comment by hsluoyz** [comment]
@Zat42 can you make a new PR with the same code change, which has fixed the issues? You can keep the original git author info but change the git comitter info to your own.

image

**Comment by ssajnani** [comment]
Sorry been off the map for a bit. Nice to see that this is in.

**Pull request closed without merging**
